dist: xenial
language: php
php:
  - '7.3'

env:
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/api?server_version=12

services:
  - postgresql

addons:
  postgresql: "12"
  
before_script: cd api/

script:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load --append --group=tests --env=test
  - php bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
    
    
    
#jobs:
#  include:
#    - language: node_js
#      node_js: 12
#      script:
#        - #TODO
