dist: xenial
language: php
php:
  - '7.3'

services:
  - postgresql

before_script:
  - cd api/
  - psql -c 'create database api;' -U postgres
  - psql -c "CREATE USER api-platform WITH PASSWORD '!ChangeMe!';" -U postgres 

script:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load --append --group=tests --env=test
  - php bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
    
    
    
#jobs:
#  include:
#    - language: node_js
#      node_js: 12
#      script:
#        - #TODO
